# Generated by Django 3.0.3 on 2020-03-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filebox', '0002_auto_20200302_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='date_posted',
            new_name='date_uploaded',
        ),
    ]
