# Generated by Django 3.0.3 on 2020-03-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filebox', '0005_auto_20200302_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='title',
            new_name='about',
        ),
    ]
